#!/bin/bash

function parseargs
{
  if [ -n $1 ]; then
    export APP_ENV=$1
  fi

  if [ -z $APP_ENV ]; then
    echo 'Please specify env.'
    exit
  fi

  export APP_HOME=/opt/rover/app
  export CATALINA_HOME=/opt/tomcat/current
  export JAVA_HOME=/opt/jdk/current
  export CATALINA_CLASSPATH=$APP_HOME/config
  export JAVA_OPTS="-Xms2048m -Xmx2048m -Dfile.encoding=UTF-8 -Dproperties.platform=$APP_ENV -Dserver.env=$APP_ENV -XX:MaxPermSize=256m -Dcom.sun.management.jmxremote -XX:-UseGCOverheadLimit -Dcom.sun.management.jmxremote.port=7002 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8586,server=y,suspend=n"
}

function start_tomcat
{
  if [ ! -e $CATALINA_HOME/bin/startup.sh ]; then
    echo '$CATALINA_HOME does not exist'
    exit
  fi
  pushd $CATALINA_HOME/bin;./startup.sh;popd;
}

parseargs $*
start_tomcat
